version: "1"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - .:/var/lib/postgresql/data
      - ./createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
    ports:
      - "5432:5432"
